#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.8
PACKAGE_NAME = SimpleAgenda
APP_NAME = SimpleAgenda
SimpleAgenda_APPLICATION_ICON = Calendar.tiff
GNUSTEP_INSTALLATION_DIR = $(HOME)/GNUstep


#
# Libraries
#
SimpleAgenda_LIBRARIES_DEPEND_UPON += -lChronographerSource 

#
# Resource files
#
SimpleAgenda_RESOURCE_FILES = \
Resources/Agenda.gorm \
Resources/Appointment.gorm \
Resources/Calendar.tiff 


#
# Header files
#
SimpleAgenda_HEADER_FILES = \
AppController.h \
AgendaStore.h \
LocalStore.h \
AppointmentEditor.h \
CalendarView.h \
Appointment+Agenda.h \
StoreManager.h \
DayView.h

#
# Class files
#
SimpleAgenda_OBJC_FILES = \
AppController.m \
LocalStore.m \
AppointmentEditor.m \
CalendarView.m \
Appointment+Agenda.m \
StoreManager.m \
DayView.m

#
# Other sources
#
SimpleAgenda_OBJC_FILES += \
SimpleAgenda.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
